/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import static org.example.app.Calculatrice.add;

public class App {
    public static void main(String[] args) {
        System.out.println(add(4,5));
    }
}
