/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CalculatriceTest {
    @Test void testAdd() {
        assertEquals(Calculatrice.add(3,5), 8);
        System.out.println("Test add Reussi !");
    }

    @Test void testMultiply() {
        assertEquals(Calculatrice.multiply(0,5),0);
        System.out.println("Test multiply Reussi !");
    }
}
